// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_tokens.sql

package sqlc

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const createAPIToken = `-- name: CreateAPIToken :exec
INSERT INTO api_tokens (id, user_id, name, prefix, secret_hash, scopes, created_at, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateAPITokenParams struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	Prefix     string
	SecretHash []byte
	Scopes     []string
	CreatedAt  time.Time
	ExpiresAt  *time.Time
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) error {
	_, err := q.db.Exec(ctx, createAPIToken,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Prefix,
		arg.SecretHash,
		arg.Scopes,
		arg.CreatedAt,
		arg.ExpiresAt,
	)
	return err
}

const getAPITokenByPrefix = `-- name: GetAPITokenByPrefix :one
SELECT t.id, t.user_id, t.name, t.prefix, t.secret_hash, t.scopes, t.created_at, t.expires_at, t.last_used_at, t.last_used_ip, t.revoked_at FROM api_tokens t
                    JOIN users u ON u.id = t.user_id
WHERE t.prefix = $1 AND u.disabled_at IS NULL
`

func (q *Queries) GetAPITokenByPrefix(ctx context.Context, prefix string) (APIToken, error) {
	row := q.db.QueryRow(ctx, getAPITokenByPrefix, prefix)
	var i APIToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Prefix,
		&i.SecretHash,
		&i.Scopes,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.LastUsedIP,
		&i.RevokedAt,
	)
	return i, err
}

const listUserAPITokens = `-- name: ListUserAPITokens :many
SELECT id, user_id, name, prefix, secret_hash, scopes, created_at, expires_at, last_used_at, last_used_ip, revoked_at FROM api_tokens WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListUserAPITokens(ctx context.Context, userID uuid.UUID) ([]APIToken, error) {
	rows, err := q.db.Query(ctx, listUserAPITokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []APIToken{}
	for rows.Next() {
		var i APIToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Prefix,
			&i.SecretHash,
			&i.Scopes,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.LastUsedIP,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIToken = `-- name: RevokeAPIToken :execrows
UPDATE api_tokens SET revoked_at = $3 WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
`

type RevokeAPITokenParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	RevokedAt *time.Time
}

func (q *Queries) RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAPIToken, arg.ID, arg.UserID, arg.RevokedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = $2, last_used_ip = $3 WHERE id = $1
`

type TouchAPITokenParams struct {
	ID         uuid.UUID
	LastUsedAt *time.Time
	LastUsedIP *netip.Addr
}

func (q *Queries) TouchAPIToken(ctx context.Context, arg TouchAPITokenParams) error {
	_, err := q.db.Exec(ctx, touchAPIToken, arg.ID, arg.LastUsedAt, arg.LastUsedIP)
	return err
}
