// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: calendars.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const countCalendars = `-- name: CountCalendars :one
SELECT count(*) FROM calendars WHERE owner_id = $1
`

func (q *Queries) CountCalendars(ctx context.Context, ownerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countCalendars, ownerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCalendar = `-- name: CreateCalendar :one
INSERT INTO calendars (id, owner_id, name, color, description, timezone, kind, read_only, hidden, position, default_reminders)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, owner_id, name, color, description, timezone, kind, read_only, is_default, hidden, position, default_reminders, created_at, updated_at
`

type CreateCalendarParams struct {
	ID               uuid.UUID
	OwnerID          uuid.UUID
	Name             string
	Color            string
	Description      string
	Timezone         *string
	Kind             string
	ReadOnly         bool
	Hidden           bool
	Position         int32
	DefaultReminders []int32
}

func (q *Queries) CreateCalendar(ctx context.Context, arg CreateCalendarParams) (Calendar, error) {
	row := q.db.QueryRow(ctx, createCalendar,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Color,
		arg.Description,
		arg.Timezone,
		arg.Kind,
		arg.ReadOnly,
		arg.Hidden,
		arg.Position,
		arg.DefaultReminders,
	)
	var i Calendar
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.Timezone,
		&i.Kind,
		&i.ReadOnly,
		&i.IsDefault,
		&i.Hidden,
		&i.Position,
		&i.DefaultReminders,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDefaultCalendar = `-- name: CreateDefaultCalendar :exec
INSERT INTO calendars (id, owner_id, name, is_default)
VALUES ($1, $2, $3, true)
`

type CreateDefaultCalendarParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
	Name    string
}

func (q *Queries) CreateDefaultCalendar(ctx context.Context, arg CreateDefaultCalendarParams) error {
	_, err := q.db.Exec(ctx, createDefaultCalendar, arg.ID, arg.OwnerID, arg.Name)
	return err
}

const deleteCalendar = `-- name: DeleteCalendar :execrows
DELETE FROM calendars WHERE id = $1 AND owner_id = $2 AND NOT is_default
`

type DeleteCalendarParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) DeleteCalendar(ctx context.Context, arg DeleteCalendarParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCalendar, arg.ID, arg.OwnerID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCalendar = `-- name: GetCalendar :one
SELECT id, owner_id, name, color, description, timezone, kind, read_only, is_default, hidden, position, default_reminders, created_at, updated_at FROM calendars WHERE id = $1 AND owner_id = $2
`

type GetCalendarParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) GetCalendar(ctx context.Context, arg GetCalendarParams) (Calendar, error) {
	row := q.db.QueryRow(ctx, getCalendar, arg.ID, arg.OwnerID)
	var i Calendar
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.Timezone,
		&i.Kind,
		&i.ReadOnly,
		&i.IsDefault,
		&i.Hidden,
		&i.Position,
		&i.DefaultReminders,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCalendarForUpdate = `-- name: GetCalendarForUpdate :one
SELECT id, owner_id, name, color, description, timezone, kind, read_only, is_default, hidden, position, default_reminders, created_at, updated_at FROM calendars WHERE id = $1 AND owner_id = $2 FOR UPDATE
`

type GetCalendarForUpdateParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
}

func (q *Queries) GetCalendarForUpdate(ctx context.Context, arg GetCalendarForUpdateParams) (Calendar, error) {
	row := q.db.QueryRow(ctx, getCalendarForUpdate, arg.ID, arg.OwnerID)
	var i Calendar
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.Timezone,
		&i.Kind,
		&i.ReadOnly,
		&i.IsDefault,
		&i.Hidden,
		&i.Position,
		&i.DefaultReminders,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCalendars = `-- name: ListCalendars :many
SELECT id, owner_id, name, color, description, timezone, kind, read_only, is_default, hidden, position, default_reminders, created_at, updated_at FROM calendars WHERE owner_id = $1 ORDER BY position, created_at, id
`

func (q *Queries) ListCalendars(ctx context.Context, ownerID uuid.UUID) ([]Calendar, error) {
	rows, err := q.db.Query(ctx, listCalendars, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Calendar{}
	for rows.Next() {
		var i Calendar
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Color,
			&i.Description,
			&i.Timezone,
			&i.Kind,
			&i.ReadOnly,
			&i.IsDefault,
			&i.Hidden,
			&i.Position,
			&i.DefaultReminders,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextCalendarPosition = `-- name: NextCalendarPosition :one
SELECT (coalesce(max(position), -1) + 1)::int AS next FROM calendars WHERE owner_id = $1
`

func (q *Queries) NextCalendarPosition(ctx context.Context, ownerID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextCalendarPosition, ownerID)
	var next int32
	err := row.Scan(&next)
	return next, err
}

const updateCalendar = `-- name: UpdateCalendar :one
UPDATE calendars
SET name = $3, color = $4, description = $5, timezone = $6, hidden = $7, position = $8, default_reminders = $9, updated_at = now()
WHERE id = $1 AND owner_id = $2
RETURNING id, owner_id, name, color, description, timezone, kind, read_only, is_default, hidden, position, default_reminders, created_at, updated_at
`

type UpdateCalendarParams struct {
	ID               uuid.UUID
	OwnerID          uuid.UUID
	Name             string
	Color            string
	Description      string
	Timezone         *string
	Hidden           bool
	Position         int32
	DefaultReminders []int32
}

func (q *Queries) UpdateCalendar(ctx context.Context, arg UpdateCalendarParams) (Calendar, error) {
	row := q.db.QueryRow(ctx, updateCalendar,
		arg.ID,
		arg.OwnerID,
		arg.Name,
		arg.Color,
		arg.Description,
		arg.Timezone,
		arg.Hidden,
		arg.Position,
		arg.DefaultReminders,
	)
	var i Calendar
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Color,
		&i.Description,
		&i.Timezone,
		&i.Kind,
		&i.ReadOnly,
		&i.IsDefault,
		&i.Hidden,
		&i.Position,
		&i.DefaultReminders,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
