// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: changes.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertChange = `-- name: InsertChange :one
INSERT INTO changes (owner_id, entity, entity_id, op, calendar_id, list_id, span, origin)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING seq
`

type InsertChangeParams struct {
	OwnerID    uuid.UUID
	Entity     string
	EntityID   uuid.UUID
	Op         string
	CalendarID *uuid.UUID
	ListID     *uuid.UUID
	Span       pgtype.Range[pgtype.Timestamptz]
	Origin     *string
}

func (q *Queries) InsertChange(ctx context.Context, arg InsertChangeParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertChange,
		arg.OwnerID,
		arg.Entity,
		arg.EntityID,
		arg.Op,
		arg.CalendarID,
		arg.ListID,
		arg.Span,
		arg.Origin,
	)
	var seq int64
	err := row.Scan(&seq)
	return seq, err
}
