// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type APIToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	Name       string
	Prefix     string
	SecretHash []byte
	Scopes     []string
	CreatedAt  time.Time
	ExpiresAt  *time.Time
	LastUsedAt *time.Time
	LastUsedIP *netip.Addr
	RevokedAt  *time.Time
}

type AuditLog struct {
	ID        int64
	UserID    *uuid.UUID
	Action    string
	IP        *netip.Addr
	UserAgent string
	Meta      []byte
	CreatedAt time.Time
}

type Calendar struct {
	ID               uuid.UUID
	OwnerID          uuid.UUID
	Name             string
	Color            string
	Description      string
	Timezone         *string
	Kind             string
	ReadOnly         bool
	IsDefault        bool
	Hidden           bool
	Position         int32
	DefaultReminders []int32
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type Change struct {
	Seq        int64
	OwnerID    uuid.UUID
	Entity     string
	EntityID   uuid.UUID
	Op         string
	CalendarID *uuid.UUID
	ListID     *uuid.UUID
	Span       pgtype.Range[pgtype.Timestamptz]
	Origin     *string
	CreatedAt  time.Time
}

type DuplicateCandidate struct {
	ID         uuid.UUID
	OwnerID    uuid.UUID
	Entity     string
	AID        uuid.UUID
	BID        uuid.UUID
	Reason     string
	Score      float32
	Status     string
	CreatedAt  time.Time
	ResolvedAt *time.Time
	ASnapshot  []byte
	BSnapshot  []byte
}

type EmailToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Purpose   string
	TokenHash []byte
	NewEmail  *string
	CreatedAt time.Time
	ExpiresAt time.Time
	UsedAt    *time.Time
}

type Event struct {
	ID           uuid.UUID
	OwnerID      uuid.UUID
	CalendarID   uuid.UUID
	IcalUID      string
	SeriesID     *uuid.UUID
	RecurrenceID *time.Time
	Title        string
	Body         string
	Location     string
	URL          string
	AllDay       bool
	StartAt      *time.Time
	EndAt        *time.Time
	StartDate    pgtype.Date
	EndDate      pgtype.Date
	Tz           *string
	Span         pgtype.Range[pgtype.Timestamptz]
	Rrule        *string
	Rdate        []time.Time
	Exdate       []time.Time
	Status       string
	Transparency string
	Visibility   string
	Color        *string
	ReadOnly     bool
	Sequence     int32
	Version      int64
	Fingerprint  []byte
	SourceHash   []byte
	CreatedAt    time.Time
	UpdatedAt    time.Time
	DeletedAt    *time.Time
	Search       interface{}
}

type EventReminder struct {
	EventID       uuid.UUID
	MinutesBefore int32
}

type GoogleAccount struct {
	ID                uuid.UUID
	UserID            uuid.UUID
	IdentityID        uuid.UUID
	RefreshTokenEnc   []byte
	Scopes            []string
	Status            string
	LastError         *string
	RevokedNotifiedAt *time.Time
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type IcsSubscription struct {
	ID              uuid.UUID
	OwnerID         uuid.UUID
	CalendarID      uuid.UUID
	URLEnc          []byte
	URLHost         string
	RefreshInterval pgtype.Interval
	NextRefreshAt   time.Time
	Status          string
	Etag            *string
	LastModified    *string
	ContentHash     []byte
	Failures        int32
	LastAttemptAt   *time.Time
	LastOkAt        *time.Time
	LastError       *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type IdempotencyKey struct {
	UserID       uuid.UUID
	Key          string
	Method       string
	Path         string
	RequestHash  []byte
	Status       *int16
	ResponseType *string
	ResponseBody []byte
	CreatedAt    time.Time
}

type Import struct {
	ID               uuid.UUID
	OwnerID          uuid.UUID
	Source           string
	Filename         string
	Status           string
	Payload          []byte
	PayloadSha256    []byte
	Options          []byte
	Preview          []byte
	Stats            []byte
	Error            *string
	TargetCalendarID *uuid.UUID
	TargetListID     *uuid.UUID
	CreatedAt        time.Time
	UpdatedAt        time.Time
	ExpiresAt        time.Time
	FinishedAt       *time.Time
}

type Job struct {
	ID          int64
	Kind        string
	Payload     []byte
	UniqueKey   *string
	Status      string
	Priority    int16
	RunAt       time.Time
	Attempts    int32
	MaxAttempts int32
	LockedBy    *string
	LockedAt    *time.Time
	LastError   *string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

type PushSubscription struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	Endpoint  string
	P256dh    string
	Auth      string
	UserAgent string
	CreatedAt time.Time
	LastOkAt  *time.Time
	Failures  int32
}

type ReminderDelivery struct {
	Entity        string
	EntityID      uuid.UUID
	OccurrenceAt  time.Time
	MinutesBefore int32
	OwnerID       uuid.UUID
	FireAt        time.Time
	PushSent      int32
	DeliveredAt   time.Time
}

type Session struct {
	ID                uuid.UUID
	TokenHash         []byte
	UserID            uuid.UUID
	CSRFSecret        []byte
	IP                *netip.Addr
	UserAgent         string
	CreatedAt         time.Time
	LastSeenAt        time.Time
	ExpiresAt         time.Time
	AbsoluteExpiresAt time.Time
	ReauthAt          *time.Time
}

type ShareLink struct {
	ID             uuid.UUID
	OwnerID        uuid.UUID
	Name           string
	TokenHash      []byte
	TokenEnc       []byte
	View           string
	PeriodDate     pgtype.Date
	Detail         string
	IncludeTodos   bool
	TzMode         string
	Version        int32
	AccessCount    int64
	LastAccessedAt *time.Time
	CreatedAt      time.Time
	UpdatedAt      time.Time
	RevokedAt      *time.Time
	ShowSleep      bool
}

type ShareLinkCalendar struct {
	ShareID    uuid.UUID
	CalendarID uuid.UUID
	OwnerID    uuid.UUID
}

type SleepSchedule struct {
	UserID    uuid.UUID
	Weekday   int16
	StartTime pgtype.Time
	EndTime   pgtype.Time
}

type SyncBinding struct {
	ID              uuid.UUID
	OwnerID         uuid.UUID
	AccountID       uuid.UUID
	Entity          string
	LocalCalendarID *uuid.UUID
	LocalListID     *uuid.UUID
	RemoteID        string
	RemoteName      string
	RemoteAccess    string
	Direction       string
	Enabled         bool
	SyncToken       *string
	UpdatedMin      *time.Time
	WatchChannelID  *string
	WatchResourceID *string
	WatchTokenHash  []byte
	WatchExpiresAt  *time.Time
	NextPollAt      time.Time
	LastSyncedAt    *time.Time
	LastError       *string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type SyncConflict struct {
	ID             uuid.UUID
	OwnerID        uuid.UUID
	BindingID      *uuid.UUID
	Entity         string
	LocalID        uuid.UUID
	RemoteID       string
	Winner         string
	LocalSnapshot  []byte
	RemoteSnapshot []byte
	CreatedAt      time.Time
}

type SyncMapping struct {
	BindingID          uuid.UUID
	Entity             string
	LocalID            uuid.UUID
	RemoteID           string
	RemoteEtag         *string
	RemoteUpdated      *time.Time
	LocalVersionAtSync int64
	RemoteDueDate      pgtype.Date
	SyncedAt           time.Time
}

type SyncOutbox struct {
	ID            int64
	BindingID     uuid.UUID
	Entity        string
	LocalID       uuid.UUID
	Op            string
	RemoteID      *string
	Attempts      int32
	NextAttemptAt time.Time
	LastError     *string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type Todo struct {
	ID             uuid.UUID
	OwnerID        uuid.UUID
	ListID         uuid.UUID
	ParentID       *uuid.UUID
	IcalUID        *string
	Title          string
	Body           string
	Status         string
	Priority       int16
	Position       string
	DueDate        pgtype.Date
	DueTime        pgtype.Time
	DurationMin    *int32
	Tz             *string
	Rrule          *string
	ShowOnCalendar bool
	CompletedAt    *time.Time
	Version        int64
	Fingerprint    []byte
	SourceHash     []byte
	CreatedAt      time.Time
	UpdatedAt      time.Time
	DeletedAt      *time.Time
	Search         interface{}
}

type TodoCheck struct {
	ID        uuid.UUID
	TodoID    uuid.UUID
	Text      string
	Done      bool
	Position  string
	DoneAt    *time.Time
	CreatedAt time.Time
}

type TodoList struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Name      string
	Color     string
	Position  int32
	IsDefault bool
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TodoReminder struct {
	TodoID        uuid.UUID
	MinutesBefore int32
}

type UndoEntry struct {
	ID        uuid.UUID
	OwnerID   uuid.UUID
	Kind      string
	Label     string
	Payload   []byte
	CreatedAt time.Time
	ExpiresAt time.Time
	UsedAt    *time.Time
}

type User struct {
	ID                   uuid.UUID
	Email                string
	EmailVerifiedAt      *time.Time
	PasswordHash         *string
	DisplayName          string
	Timezone             string
	WeekStart            int16
	TimeFormat           string
	DefaultView          string
	DateOnlyReminderTime pgtype.Time
	DedupPolicy          string
	CreatedAt            time.Time
	UpdatedAt            time.Time
	DisabledAt           *time.Time
	SleepEnabled         bool
}

type UserIdentity struct {
	ID       uuid.UUID
	UserID   uuid.UUID
	Provider string
	Subject  string
	Email    string
	LinkedAt time.Time
}
