// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	CountCalendars(ctx context.Context, ownerID uuid.UUID) (int64, error)
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) error
	CreateCalendar(ctx context.Context, arg CreateCalendarParams) (Calendar, error)
	CreateDefaultCalendar(ctx context.Context, arg CreateDefaultCalendarParams) error
	CreateDefaultTodoList(ctx context.Context, arg CreateDefaultTodoListParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCalendar(ctx context.Context, arg DeleteCalendarParams) (int64, error)
	DeleteExpiredSessions(ctx context.Context, now time.Time) (int64, error)
	DeleteSession(ctx context.Context, arg DeleteSessionParams) (int64, error)
	DeleteUserSessionsExcept(ctx context.Context, arg DeleteUserSessionsExceptParams) (int64, error)
	GetAPITokenByPrefix(ctx context.Context, prefix string) (APIToken, error)
	GetCalendar(ctx context.Context, arg GetCalendarParams) (Calendar, error)
	GetCalendarForUpdate(ctx context.Context, arg GetCalendarForUpdateParams) (Calendar, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	InsertAudit(ctx context.Context, arg InsertAuditParams) error
	InsertChange(ctx context.Context, arg InsertChangeParams) (int64, error)
	ListCalendars(ctx context.Context, ownerID uuid.UUID) ([]Calendar, error)
	ListUserAPITokens(ctx context.Context, userID uuid.UUID) ([]APIToken, error)
	ListUserSessions(ctx context.Context, userID uuid.UUID) ([]Session, error)
	ListUsers(ctx context.Context) ([]User, error)
	NextCalendarPosition(ctx context.Context, ownerID uuid.UUID) (int32, error)
	RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) (int64, error)
	SetSessionReauth(ctx context.Context, arg SetSessionReauthParams) error
	SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) (int64, error)
	SetUserPassword(ctx context.Context, arg SetUserPasswordParams) (int64, error)
	TouchAPIToken(ctx context.Context, arg TouchAPITokenParams) error
	TouchSession(ctx context.Context, arg TouchSessionParams) error
	UpdateCalendar(ctx context.Context, arg UpdateCalendarParams) (Calendar, error)
}

var _ Querier = (*Queries)(nil)
