// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package sqlc

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (id, token_hash, user_id, csrf_secret, ip, user_agent, created_at, last_seen_at, expires_at, absolute_expires_at, reauth_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
`

type CreateSessionParams struct {
	ID                uuid.UUID
	TokenHash         []byte
	UserID            uuid.UUID
	CSRFSecret        []byte
	IP                *netip.Addr
	UserAgent         string
	CreatedAt         time.Time
	LastSeenAt        time.Time
	ExpiresAt         time.Time
	AbsoluteExpiresAt time.Time
	ReauthAt          *time.Time
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.TokenHash,
		arg.UserID,
		arg.CSRFSecret,
		arg.IP,
		arg.UserAgent,
		arg.CreatedAt,
		arg.LastSeenAt,
		arg.ExpiresAt,
		arg.AbsoluteExpiresAt,
		arg.ReauthAt,
	)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at < $1 OR absolute_expires_at < $1
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, now time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, now)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSession = `-- name: DeleteSession :execrows
DELETE FROM sessions WHERE id = $1 AND user_id = $2
`

type DeleteSessionParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteSession(ctx context.Context, arg DeleteSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSession, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUserSessionsExcept = `-- name: DeleteUserSessionsExcept :execrows
DELETE FROM sessions WHERE user_id = $1 AND id <> $2
`

type DeleteUserSessionsExceptParams struct {
	UserID uuid.UUID
	ID     uuid.UUID
}

func (q *Queries) DeleteUserSessionsExcept(ctx context.Context, arg DeleteUserSessionsExceptParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserSessionsExcept, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT s.id, s.token_hash, s.user_id, s.csrf_secret, s.ip, s.user_agent, s.created_at, s.last_seen_at, s.expires_at, s.absolute_expires_at, s.reauth_at FROM sessions s
                    JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND u.disabled_at IS NULL
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash []byte) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.CSRFSecret,
		&i.IP,
		&i.UserAgent,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.AbsoluteExpiresAt,
		&i.ReauthAt,
	)
	return i, err
}

const listUserSessions = `-- name: ListUserSessions :many
SELECT id, token_hash, user_id, csrf_secret, ip, user_agent, created_at, last_seen_at, expires_at, absolute_expires_at, reauth_at FROM sessions WHERE user_id = $1 ORDER BY last_seen_at DESC
`

func (q *Queries) ListUserSessions(ctx context.Context, userID uuid.UUID) ([]Session, error) {
	rows, err := q.db.Query(ctx, listUserSessions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.TokenHash,
			&i.UserID,
			&i.CSRFSecret,
			&i.IP,
			&i.UserAgent,
			&i.CreatedAt,
			&i.LastSeenAt,
			&i.ExpiresAt,
			&i.AbsoluteExpiresAt,
			&i.ReauthAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSessionReauth = `-- name: SetSessionReauth :exec
UPDATE sessions SET reauth_at = $2 WHERE id = $1
`

type SetSessionReauthParams struct {
	ID       uuid.UUID
	ReauthAt *time.Time
}

func (q *Queries) SetSessionReauth(ctx context.Context, arg SetSessionReauthParams) error {
	_, err := q.db.Exec(ctx, setSessionReauth, arg.ID, arg.ReauthAt)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = $2, expires_at = $3 WHERE id = $1
`

type TouchSessionParams struct {
	ID         uuid.UUID
	LastSeenAt time.Time
	ExpiresAt  time.Time
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.ID, arg.LastSeenAt, arg.ExpiresAt)
	return err
}
