// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: todo_lists.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createDefaultTodoList = `-- name: CreateDefaultTodoList :exec
INSERT INTO todo_lists (id, owner_id, name, is_default)
VALUES ($1, $2, $3, true)
`

type CreateDefaultTodoListParams struct {
	ID      uuid.UUID
	OwnerID uuid.UUID
	Name    string
}

func (q *Queries) CreateDefaultTodoList(ctx context.Context, arg CreateDefaultTodoListParams) error {
	_, err := q.db.Exec(ctx, createDefaultTodoList, arg.ID, arg.OwnerID, arg.Name)
	return err
}
