// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, email_verified_at, password_hash, display_name, timezone)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, email_verified_at, password_hash, display_name, timezone, week_start, time_format, default_view, date_only_reminder_time, dedup_policy, created_at, updated_at, disabled_at, sleep_enabled
`

type CreateUserParams struct {
	ID              uuid.UUID
	Email           string
	EmailVerifiedAt *time.Time
	PasswordHash    *string
	DisplayName     string
	Timezone        string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.EmailVerifiedAt,
		arg.PasswordHash,
		arg.DisplayName,
		arg.Timezone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Timezone,
		&i.WeekStart,
		&i.TimeFormat,
		&i.DefaultView,
		&i.DateOnlyReminderTime,
		&i.DedupPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
		&i.SleepEnabled,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, email_verified_at, password_hash, display_name, timezone, week_start, time_format, default_view, date_only_reminder_time, dedup_policy, created_at, updated_at, disabled_at, sleep_enabled FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Timezone,
		&i.WeekStart,
		&i.TimeFormat,
		&i.DefaultView,
		&i.DateOnlyReminderTime,
		&i.DedupPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
		&i.SleepEnabled,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, email_verified_at, password_hash, display_name, timezone, week_start, time_format, default_view, date_only_reminder_time, dedup_policy, created_at, updated_at, disabled_at, sleep_enabled FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailVerifiedAt,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Timezone,
		&i.WeekStart,
		&i.TimeFormat,
		&i.DefaultView,
		&i.DateOnlyReminderTime,
		&i.DedupPolicy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DisabledAt,
		&i.SleepEnabled,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, email_verified_at, password_hash, display_name, timezone, week_start, time_format, default_view, date_only_reminder_time, dedup_policy, created_at, updated_at, disabled_at, sleep_enabled FROM users ORDER BY created_at, id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.EmailVerifiedAt,
			&i.PasswordHash,
			&i.DisplayName,
			&i.Timezone,
			&i.WeekStart,
			&i.TimeFormat,
			&i.DefaultView,
			&i.DateOnlyReminderTime,
			&i.DedupPolicy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DisabledAt,
			&i.SleepEnabled,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserDisabled = `-- name: SetUserDisabled :execrows
UPDATE users SET disabled_at = $2, updated_at = now() WHERE id = $1
`

type SetUserDisabledParams struct {
	ID         uuid.UUID
	DisabledAt *time.Time
}

func (q *Queries) SetUserDisabled(ctx context.Context, arg SetUserDisabledParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserDisabled, arg.ID, arg.DisabledAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setUserPassword = `-- name: SetUserPassword :execrows
UPDATE users SET password_hash = $2, updated_at = now() WHERE id = $1
`

type SetUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash *string
}

func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserPassword, arg.ID, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
